title: Mischa Batelaan
author: Mischa Batelaan
subtitle: personal site

url: "//mischabatelaan.com"
# url: "http://mischabatelaan.com"
# url: "https://mbatelaan.github.io"
baseurl: ""
blogurl: "/blog"

footer_only_homepage: true
# footer_url: "https://"
# footer_text: ""

profile-picture: assets/profile.webp
favicon_location: assets/favicon.ico

permalink: /blog/:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Research"
   link: "research"
 - name: "Blog"
   link: "blog"
 - name: "Fun"
   link: "fun"
 # - name: "Resume"
 #   absolute-link: "https://.pdf"

lsi: false
safe: true
# source: mbatelaan
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

collections:
  "1000":
    output: true
    permalink: /:collection/:title/
  "research":
    output: true
    permalink: /:collection/:title/
  "shorts":
    output: true
    permalink: /:collection/:title/
  # blog:
  #   permalink: /blog/:year-:month-:day-:title/
    
